import { Channel } from '../types';

export const MOCK_CHANNELS: Channel[] = [
  {
    id: '1',
    name: 'Minecraft Tutorials 2012',
    avatar: 'https://picsum.photos/seed/mc2012/200/200',
    subscribers: '12.4K',
    lastUpload: '9 years ago',
    lastUploadDate: new Date('2014-05-20'),
    description: 'Best HD tutorials for redstone and building houses!',
    category: 'Gaming',
    isInactive: true,
  },
  {
    id: '2',
    name: 'Tech Daily',
    avatar: 'https://picsum.photos/seed/tech/200/200',
    subscribers: '4.2M',
    lastUpload: '3 hours ago',
    lastUploadDate: new Date('2024-05-20'),
    description: 'Reviewing the latest gadgets and software updates every day.',
    category: 'Tech',
    isInactive: false,
  },
  {
    id: '3',
    name: 'Funny Cat Compilationz',
    avatar: 'https://picsum.photos/seed/cat/200/200',
    subscribers: '850K',
    lastUpload: '4 years ago',
    lastUploadDate: new Date('2020-01-15'),
    description: 'Just funny cats. Subscribe for more!',
    category: 'Entertainment',
    isInactive: true,
  },
  {
    id: '4',
    name: 'Coding Wizardry',
    avatar: 'https://picsum.photos/seed/code/200/200',
    subscribers: '300K',
    lastUpload: '2 days ago',
    lastUploadDate: new Date('2024-05-18'),
    description: 'Deep dives into React, Node.js and system design.',
    category: 'Education',
    isInactive: false,
  },
  {
    id: '5',
    name: 'Vlog Life Jessica',
    avatar: 'https://picsum.photos/seed/vlog/200/200',
    subscribers: '1.1M',
    lastUpload: '6 years ago',
    lastUploadDate: new Date('2018-03-10'),
    description: 'Follow my daily life in college! (Inactive)',
    category: 'Vlog',
    isInactive: true,
  },
  {
    id: '6',
    name: 'Epic Dubstep Mixes',
    avatar: 'https://picsum.photos/seed/dubstep/200/200',
    subscribers: '2.5M',
    lastUpload: '8 years ago',
    lastUploadDate: new Date('2016-11-20'),
    description: 'Drop the bass. Copyright free music 2016.',
    category: 'Music',
    isInactive: true,
  },
  {
    id: '7',
    name: 'SpaceX Fanclub',
    avatar: 'https://picsum.photos/seed/space/200/200',
    subscribers: '500K',
    lastUpload: '1 week ago',
    lastUploadDate: new Date('2024-05-10'),
    description: 'Tracking every launch and landing.',
    category: 'Science',
    isInactive: false,
  },
  {
    id: '8',
    name: 'Healthy Cooking 101',
    avatar: 'https://picsum.photos/seed/cook/200/200',
    subscribers: '25K',
    lastUpload: '2 years ago',
    lastUploadDate: new Date('2022-02-01'),
    description: 'Simple recipes for busy people.',
    category: 'Lifestyle',
    isInactive: true,
  }
];